Repository Kernel360/KDEV4-WHERE-CAR-FE, pull requests merged in 2025-04, with the labels that each got.

#2 [#1] feat: 공통 레이아웃 구현 및 메인 페이지(dashboard) 구현
  src/app/companies/page.tsx
  src/app/layout.tsx
  src/app/logs/page.tsx
  src/app/page.tsx
  src/app/vehicles/page.tsx
  src/components/common/PageHeader.tsx
  src/components/dashboard/StatCard.tsx
  src/components/layout/PageLayout.tsx
  src/components/layout/Sidebar.tsx
  src/components/providers/ClientProvider.tsx
  src/contexts/ThemeContext.tsx
Labels: feat

#5 [#4] chore: reviewers 자동등록 워크플로우 추가
  .github/workflows/reviewer-auto-registration.yml
Labels: chore

#7 [#6] fix: 라이브러리 누락 설정 추가
  package-lock.json
  package.json
Labels: fix

#9 [#8] feat: 사이드바 중복 수정 및 호버 기능 추가
  src/app/companies/page.tsx
  src/app/layout.tsx
  src/app/logs/page.tsx
  src/app/page.tsx
  src/app/vehicles/page.tsx
  src/components/common/PageHeader.tsx
  src/components/layout/Sidebar.tsx
Labels: fix, feat

#11 [#10] remove: 점검 예정 차량 컴포넌트 제거
  src/app/logs/page.tsx
  src/app/page.tsx
Labels: remove

#14 [#3] feat: 차량 관리 페이지 구현
  package-lock.json
  package.json
  src/app/vehicles/page.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/contexts/ThemeContext.tsx
Labels: feat

#18 [#15] feat: 운행일지 페이지 구현
  package-lock.json
  package.json
  src/app/logs/page.tsx
  src/app/page.tsx
  src/app/vehicles/page.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/logs/VehicleLogFilter.tsx
  src/components/logs/VehicleLogList.tsx
  src/components/ui/button.tsx
  src/components/ui/date-picker.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
  src/components/ui/table.tsx
  src/lib/utils.ts
  src/types/logs.ts
Labels: feat

#21 [#19] feat: zustand 설치 및 운행일지 목록 api 연결
  next.config.mjs
  package-lock.json
  package.json
  src/app/logs/page.tsx
  src/components/logs/VehicleLogList.tsx
  src/lib/api.ts
  src/lib/carLogsStore.ts
  src/types/logs.ts
Labels: feat

#25 [#23] feat: 운행일지 페이지 API 연결
  src/app/logs/page.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/logs/VehicleLogFilter.tsx
  src/components/logs/VehicleLogList.tsx
  src/components/ui/date-picker.tsx
  src/lib/carLogsStore.ts
  src/lib/utils.ts
  src/types/logs.ts
Labels: feat

#29 [#28] fix: 배포 테스트 및 빌드 디버깅
  next.config.mjs
  package-lock.json
  package.json
  src/app/companies/page.tsx
  src/app/employees/add/page.tsx
  src/app/layout.tsx
  src/app/logs/page.tsx
  src/app/page.tsx
  src/app/permissions/[employeeId]/page.tsx
  src/app/vehicles/page.tsx
  src/components/common/EmployeeDetailPanel.tsx
  src/components/common/ToastContainer.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/vehicles/VehicleAddModal.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/contexts/ToastContext.tsx
  src/lib/api.ts
  src/lib/carLogsStore.ts
  src/lib/employeeStore.ts
  src/lib/userStore.ts
  src/store/vehicleStore.ts
Labels: fix, feat, chore

#32 [#31] feat: 대쉬보드 차량 api, 사용자 api 연결
  package-lock.json
  package.json
  src/app/page.tsx
  src/app/vehicles/page.tsx
  src/components/logs/VehicleLogFilter.tsx
  src/components/vehicles/VehicleAddModal.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/lib/carOverviewStore.ts
  src/lib/vehicleStore.ts
Labels: feat

#33 [#30] feat: 로그인, 회원가입 구현 및 기타수정
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/logs/page.tsx
  src/app/page.tsx
  src/app/register/layout.tsx
  src/app/register/page.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/logs/VehicleLogList.tsx
  src/contexts/ThemeContext.tsx
  src/lib/api.ts
  src/lib/authStore.ts
  src/lib/carLogsStore.ts
  src/lib/companyStore.ts
  src/lib/employeeStore.ts
  src/lib/registerStore.ts
  src/lib/userStore.ts
  src/lib/utils.ts
  src/middleware.ts
Labels: fix, feat

#35 [#34] feat: 메인페이지 생성
  src/app/dashboard/page.tsx
  src/app/login/layout.tsx
  src/app/page.tsx
  src/app/register/layout.tsx
  src/components/layout/PageLayout.tsx
  src/components/layout/Sidebar.tsx
  src/lib/authStore.ts
  src/middleware.ts
Labels: feat

#37 [#36] feat: 프로필 페이지 추가
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/register/page.tsx
  src/components/layout/Sidebar.tsx
  src/middleware.ts
Labels: feat

#39 [#38] fix: car, carLog fetch 주소 api 누락 수정
  src/app/companies/page.tsx
  src/app/layout.tsx
  src/app/logs/page.tsx
  src/app/profile/page.tsx
  src/app/register/layout.tsx
  src/app/register/page.tsx
  src/app/vehicles/page.tsx
  src/components/common/AlertMessage.tsx
  src/components/common/EmployeeDetailPanel.tsx
  src/components/common/ToastContainer.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/logs/VehicleLogList.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/contexts/ToastContext.tsx
  src/lib/carOverviewStore.ts
  src/lib/vehicleStore.ts
Labels: fix

#56 [#47] feat: 운행일지, 차량 상세 페이지 지도 구현
  components.json
  package-lock.json
  package.json
  public/index.html
  src/app/globals.css
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/map/NaverMap.tsx
  src/components/map/RouteMap.tsx
  src/components/ui/alert.tsx
  src/components/vehicles/NaverMap.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/lib/api.ts
  src/lib/utils.ts
  src/lib/vehicleStore.ts
  src/types/global.d.ts
Labels: feat

#58 [#57] fix: 에러 해결, 지도 수정, 환경변수 추가
  README.md
  next.config.mjs
  public/index.html
  src/app/permissions/[employeeId]/page.tsx
  src/app/profile/page.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/map/NaverMap.tsx
  src/components/map/RouteMap.tsx
  src/components/map/VehicleLocationMap.tsx
  src/components/vehicles/NaverMap.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/lib/api.ts
  src/lib/env.ts
Labels: fix, feat

#60 [#59] feat: 실시간 차량 위치 조회 페이지 구현 및 웹소켓 연결
  src/app/monitoring/page.tsx
  src/components/common/PageHeader.tsx
  src/components/layout/Sidebar.tsx
  src/components/map/CarMap.tsx
  src/contexts/ThemeContext.tsx
Labels: feat

#65 [#63] feat: 차량 실시간 위치 페이지 지도 ui 변경
  src/app/monitoring/page.tsx
  src/components/map/CarMap.tsx
Labels: feat

#82 [#81] fix: API 호출을 기본바디에서 BaseResponse 로 변경
  src/app/logs/page.tsx
  src/app/profile/page.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/logs/VehicleLogFilter.tsx
  src/components/logs/VehicleLogList.tsx
  src/lib/announcementStore.ts
  src/lib/authStore.ts
  src/lib/carLogsStore.ts
  src/lib/carOverviewStore.ts
  src/lib/companyStore.ts
  src/lib/userStore.ts
  src/lib/vehicleStore.ts
  src/types/logs.ts
Labels: fix

#74 [#71] feat: refresh 기반 access토큰 갱신 로직 구현
  src/components/layout/Sidebar.tsx
  src/lib/api.ts
  src/lib/authStore.ts
Labels: feat

#77 [#75] feat: 차량 관제 페이지 경로 보기 기능 추가
  src/app/monitoring/page.tsx
  src/components/map/CarMap.tsx
  src/components/map/NaverMap.tsx
  src/components/vehicles/RouteMap.tsx
Labels: feat

#88 [#85] 차량 실시간 위치/상세 정보 관련 기능 및 UI 수정
  src/app/monitoring/page.tsx
  src/components/logs/VehicleLogDetailSlidePanel.tsx
  src/components/vehicles/VehicleDetailSlidePanel.tsx
  src/lib/api.ts
  src/pages/api/vehicle/position.ts
Labels: feat

#90 [#89] fix: 프론트 QA
  src/app/companies/page.tsx
  src/app/dashboard/page.tsx
  src/components/layout/Sidebar.tsx
  src/lib/carLogsStore.ts
Labels: feat

#84 [#83] feat: 대시보드 페이지에 user 자세히 버튼 추가
  DashboardPage.jsx
  src/app/dashboard/page.tsx
Labels: feat

#92 [#91] feat: 유효하지 않은 토큰 삭제 및 리다이렉트
  src/lib/authStore.ts
  src/lib/env.ts
Labels: feat
